186 storychunk files should have chronicle name story name and client ip
scs-lab/ChronoLog pull request #187
Opened 2024-08-19 13:56 UTC by fkengun

Changes in this PR:
- Fix missed renaming of Logger class, even for commented targets
- Persisted result files from ChronoGrapher are now named as "chronicle_name.story_name.client_ip.start_time/1000000000.csv"

2024-08-21 05:35 UTC, fkengun commented
`KeeperDataStore.cpp` in Grapher is now renamed to `GrapherDataStore.cpp` to avoid ambiguity.

2024-08-22 20:56 UTC, ibrodkin requested changes
I do not thin that we should be adding ClientIP to hte StoryPipeline or to the StoryChunk classes. This goes against our basic definition of the story as beingthe collection of events attributed to the story by different clients running on different hosts 

Please reverse the client ip changes.

2024-08-23 22:18 UTC, EnekoGonzalez3 commented
Please, merge new updates on develop branch to test changes with the new local script.

2024-08-23 22:37 UTC, EnekoGonzalez3 commented on ChronoGrapher/CMakeLists.txt
KeeperDataStore appears as deleted, but there is no GrapherDataStore.

2024-08-24 14:06 UTC, fkengun commented on ChronoGrapher/CMakeLists.txt
> KeeperDataStore appears as deleted, but there is no GrapherDataStore.

For some reason, CLion failed to recognize the renaming. I had to redo the changes since these two files were lost after I switched to another branch.

2024-09-07 12:28 UTC, EnekoGonzalez3 approved these changes

2024-09-13 15:22 UTC, ibrodkin approved these changes

2024-09-13 15:23 UTC, merged