Integrate HDF5 archiver to extract StoryChunks
scs-lab/ChronoLog pull request #220
Opened 2024-11-01 21:57 UTC by fkengun

**Summary:**
Integrate HDF5 archiver to the existing data pipeline in Grapher following most of the design in https://docs.google.com/drawings/d/1N2x9mtqL9y2m-ns5EH3mH4boPEaHiz-GzaV7nPRV2hQ/edit. Please notice the highlighted new StoryChunk and LogEvent definitions.

**Changes:**
- Archive StoryChunks in HDF5 files using HDF5 vlen data type. In order to do this, two new versions of StoryChunk and LogEvent are added on the side of the existing two
- Add Thread-safe support to HDF5 dependency as a requirement to write multiple HDF5 files in multiple threads

**Notes:**
Each file only has one dataset for one StoryChunk in this version. Thus, each Story is spread into across multiple files instead of being stored in a single file.

2024-11-08 17:30 UTC, EnekoGonzalez3 approved these changes

2024-11-12 22:38 UTC, ibrodkin requested changes
see the comments inlined

2024-11-12 22:38 UTC, ibrodkin commented on chrono_common/chronolog_types.h
> +    {
I would define operator< () in terms of  eventTime+clientId+eventIndex  to be consistent with the ordering we use in  other places.

2024-11-12 22:38 UTC, ibrodkin commented on chrono_common/chronolog_types.h
> +        for(hsize_t i = 0; i < logRecord.len; i++)
I don't think operator== () should include conparison of the data part of the LogEvent . Please, limit comparison to storyId+eventTime+clientId+eventIndex

2024-11-12 22:38 UTC, ibrodkin commented on ChronoGrapher/HDF5FileChunkExtractor.h
> +#include "StoryChunkWriter.h"
"StoryChunkExtractor.h" is the only file needed to be included here

2024-11-12 22:38 UTC, ibrodkin commented on ChronoGrapher/StoryChunkWriter.cpp
> +        sleep(1);
is sleep(1) needed here or is it a debugging leftover?

2024-11-12 22:38 UTC, ibrodkin commented on ChronoGrapher/StoryChunkWriter.cpp
> +        LOG_ERROR("[StoryChunkWriter] FileIException: {}", error.getCDetailMsg());
memory allocated for file within the try{}  paragraph is leaked in case the exception caught

2024-11-12 22:38 UTC, ibrodkin commented on ChronoGrapher/StoryChunkWriter.cpp
> +        event_hvl.storyId = event.second.getStoryId();
it seems event_hvl constructor should be used here, cleaner looking code and faster execution than 5 lines of assignment operators

2024-11-12 22:38 UTC, ibrodkin commented on ChronoGrapher/StoryChunkWriter.cpp
> +        H5::FileIException::printErrorStack();
file pointer memory leak, same case as line 37

2024-11-12 22:38 UTC, ibrodkin commented on ChronoGrapher/StoryChunkWriter.cpp
> +    for(auto &event: data)
what is the reason to iterate through the data vector here? The destructor for each event object would be called as the data vector goes out of scope and take care of each event memory allocation

2024-11-15 21:05 UTC, ibrodkin reviewed
one small change ( see comments about using tuple for comparison)

otherwise looks good

2024-11-15 21:05 UTC, ibrodkin commented on chrono_common/chronolog_types.h
> +        return std::make_tuple(eventTime, clientId, eventIndex) <
i don't think calling std::tuple constructor twice here is justified, simple comparison of 3 integers would do here

2024-11-18 17:43 UTC, ibrodkin approved these changes

2024-11-19 01:13 UTC, EnekoGonzalez3 approved these changes

2024-11-19 01:14 UTC, merged